---
- name: Install required packages
  apt:
          state: present
          name: 
                  - dirmngr
                  - gnupg
                  - apt-transport-https
                  - ca-certificates
                  - software-properties-common

- name: Import public GPG key for the latest stable version of MongoDB
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=9DA31620334BD75D9DCB49F368818C72E52529D4 state=present
  
- name: Add MongoDB Repository
  apt_repository: 
    repo: 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse' 
    state: present
    update_cache: yes

- name: Install MongoDB
  apt: 
    name: mongodb-org 
    state: present
    update_cache: yes

- name: Start MongoDB
  shell: "mongod &"