---
- name: Install git
  apt: 
     name: git
     state: present
     update_cache: yes

- name: Check if the git repository exists
  stat: path=/opt/yolo
  register: repo_stat

- name: Fetch the kitmikai/yolo GitHub repository
  git:
          repo: https://github.com/kitmikai/yolo.git
          dest: /opt/yolo
  when: not repo_stat.stat.exists